# PostgreSQL 数据库服务
# 可被多个应用共享使用
services:
  postgres:
    image: postgres:18
    container_name: postgres
    restart: unless-stopped
    env_file:
      - ../../../.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-qiudeng}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      # - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_DATABASES=${POSTGRES_DATABASES:-}
    volumes:
      - postgres-data:/var/lib/postgresql
      - ./initdb.d:/docker-entrypoint-initdb.d:ro
      - ./modified-docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh:ro
    networks:
      - selfhost
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-qiudeng}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:

networks:
  selfhost:
    external: true
    name: selfhost
