apiVersion: v1
kind: Service
metadata:
  name: garage
  labels:
    app: garage
spec:
  type: NodePort
  ports:
    - port: 3900
      targetPort: 3900
      name: s3-endpoint
      nodePort: 30390
    - port: 3901
      targetPort: 3901
      name: rpc
      nodePort: 30391
    - port: 3902
      targetPort: 3902
      name: s3-web
      nodePort: 30392
    - port: 3903
      targetPort: 3903
      name: admin
      nodePort: 30393
  selector:
    app: garage
---
apiVersion: v1
kind: Service
metadata:
  name: garage-webui
  labels:
    app: garage-webui
spec:
  type: NodePort
  ports:
    - port: 3909
      targetPort: 3909
      name: webui
      nodePort: 30399
  selector:
    app: garage-webui