apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: garage

resources:
  - namespace.yaml
  - configmap.yaml
  - pvc.yaml
  - deployment-garage.yaml
  - deployment-garage-webui.yaml
  - service.yaml

labels:
  - pairs:
      app.kubernetes.io/name: garage
      app.kubernetes.io/component: object-storage
