# Nextflux 服务
services:
  nextflux:
    image: electh/nextflux
    container_name: nextflux
    restart: always
    networks:
      - selfhost

networks:
  selfhost:
    external: true
    name: selfhost
